### ISSUE TITLE
Remove package-lock.json

### ISSUE THREAD

**Issue by GabrielVander** [IFSP-PW4/pw4-project-backend#5]
Since the majority voted to use yarn as a package manager we can delete the package-lock.json file created  by npm.

**Comment by Adeola-Adesoba** [comment]
Hi, I will like to help with removing the file, is that what the task means?

**Comment by GabrielVander** [comment]
Hi @Adeola-Adesoba. Yes that's exactly what the task means. Unfortunately this is a group project for a certain subject in our university in Brazil. That means that for you to be involved in the project we'll need our professor's approval. He has already been contacted, and we're waiting his response. In the meantime please feel free to implement this issue and submit a pull request. Please note that it **must** be implemented in a new branch created from the **develop** branch. When you're done you can submit a pull request - please assign me as the reviewer. With that been said I cannot guarantee that your changes will make it to the master branch - a.k.a. production - nor that you'll be allowed to implement other features as it is subject to our professor's judgment. As soon as we receive a response from him we'll contact you - either through the pull request or through here. But please be assured that whatever the response maybe we're delighted by your willingness to cooperate. Thank you! Looking forward for your PR!

**Comment by Adeola-Adesoba** [comment]
Hi @GabrielVander , thank you so much for responding. I understand that this is a group project and also the importance of getting your Professor's approval. I am just glad I could help and not worried if my changes will make it to production or not.

I have created the PR but I can not add you as a Reviewer. I don't know why that is but I think that I am not authorized to.

**Comment by GabrielVander** [comment]
Humm yes it seems you must be a member to assign a reviewer, no worries I can still assign it to myself. I'll review it but I'll only merge it when I get a response from him, ok?

**Comment by Adeola-Adesoba** [comment]
Thank you @GabrielVander , I got your email. glad to see the changes approved. Let me know if there is anything else I can help with.

**Comment by GabrielVander** [comment]
No problem, thank you for your cooperation!
